#!/bin/bash

# Проверяем, что передан путь к файлу
if [ $# -ne 1 ]; then
    echo "Usage: $0 <message_file>"
    exit 1
fi

# Проверяем существование файла
if [ ! -f "$1" ]; then
    echo "File not found: $1"
    exit 1
fi
echo "File found: $1, mark as valid"

# Всегда возвращаем успех
exit 0 